/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartLinkPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  visibleCollections: [],
  maxResults: 50,
  defaultCollection: ""
};

// src/settingsTab.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var COLLECTION_MAP = {
  "Content/Claims": "claims",
  "Content/Concepts": "concepts",
  "Content/Maps": "maps",
  "Content/Posts": "posts",
  "Content/Insights": "insights",
  "Sources/Books": "books",
  "Sources/Journals": "journals",
  "Sources/Research": "research"
};
function getCollection(filePath) {
  let best = "";
  let bestLen = -1;
  for (const [prefix, label] of Object.entries(COLLECTION_MAP)) {
    if (filePath.startsWith(prefix + "/") && prefix.length > bestLen) {
      best = label;
      bestLen = prefix.length;
    }
  }
  return best || "other";
}
var ALL_COLLECTIONS = Object.values(COLLECTION_MAP);

// src/settingsTab.ts
var SmartLinkSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smart Link Settings" });
    new import_obsidian.Setting(containerEl).setName("Max results").setDesc("Maximum number of results to show in the modal").addSlider(
      (slider) => slider.setLimits(10, 100, 5).setValue(this.plugin.settings.maxResults).onChange(async (value) => {
        this.plugin.settings.maxResults = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default collection").setDesc("Collection to show by default when opening the picker (leave empty for 'All')").addDropdown((dropdown) => {
      dropdown.addOption("", "All");
      for (const collection of ALL_COLLECTIONS) {
        dropdown.addOption(collection, collection);
      }
      dropdown.setValue(this.plugin.settings.defaultCollection).onChange(async (value) => {
        this.plugin.settings.defaultCollection = value;
        await this.plugin.saveSettings();
      });
    });
    containerEl.createEl("h3", { text: "Visible Collections" });
    containerEl.createEl("p", { text: "Check to show collections in the filter pills" });
    for (const collection of ALL_COLLECTIONS) {
      new import_obsidian.Setting(containerEl).setName(collection).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.visibleCollections.includes(collection)).onChange(async (value) => {
          const idx = this.plugin.settings.visibleCollections.indexOf(collection);
          if (value && idx === -1) {
            this.plugin.settings.visibleCollections.push(collection);
          } else if (!value && idx !== -1) {
            this.plugin.settings.visibleCollections.splice(idx, 1);
          }
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// src/views/smartLinkModal.ts
var import_obsidian2 = require("obsidian");
var SmartLinkModal = class extends import_obsidian2.SuggestModal {
  constructor(app, editor, settings) {
    super(app);
    this.activeCollection = "";
    this.index = /* @__PURE__ */ new Map();
    this.pillBar = null;
    this.allFiles = [];
    this.editor = editor;
    this.settings = settings;
    this.modalEl.addClass("smart-link-modal");
  }
  onOpen() {
    this.allFiles = this.app.vault.getMarkdownFiles();
    for (const file of this.allFiles) {
      const cache = this.app.metadataCache.getFileCache(file);
      const composite = this.buildCompositeString(file, cache);
      this.index.set(file, composite);
    }
    this.activeCollection = this.settings.defaultCollection;
    this.pillBar = this.modalEl.createDiv({ cls: "smart-link-pill-bar" });
    this.modalEl.prepend(this.pillBar);
    this.renderPills();
    super.onOpen();
    setTimeout(() => this.inputEl.focus(), 10);
  }
  buildCompositeString(file, cache) {
    var _a, _b, _c, _d;
    const fm = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
    const parts = [
      file.basename,
      String((_b = fm.title) != null ? _b : "").trim(),
      Array.isArray(fm.aliases) ? fm.aliases.join(" ") : String((_c = fm.aliases) != null ? _c : "").trim(),
      String((_d = fm.description) != null ? _d : "").trim()
    ];
    return parts.filter(Boolean).join(" | ");
  }
  getSuggestions(query) {
    var _a;
    let candidates = [...this.allFiles];
    if (this.activeCollection) {
      candidates = candidates.filter(
        (f) => getCollection(f.path) === this.activeCollection
      );
    }
    const visibleCollections = this.settings.visibleCollections;
    if (visibleCollections.length > 0) {
      candidates = candidates.filter((f) => {
        const col = getCollection(f.path);
        return visibleCollections.includes(col);
      });
    }
    if (!query.trim()) {
      return candidates.slice(0, this.settings.maxResults);
    }
    const matcher = (0, import_obsidian2.prepareFuzzySearch)(query);
    const scored = [];
    for (const file of candidates) {
      const composite = (_a = this.index.get(file)) != null ? _a : file.basename;
      const result = matcher(composite);
      if (result) {
        scored.push({ file, score: result.score });
      }
    }
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, this.settings.maxResults).map((s) => s.file);
  }
  renderSuggestion(file, el) {
    var _a;
    const collection = getCollection(file.path);
    const topLine = el.createDiv({ cls: "smart-link-result-top" });
    topLine.createEl("span", { text: file.basename, cls: "smart-link-result-title" });
    if (collection) {
      topLine.createEl("span", {
        text: collection,
        cls: "smart-link-result-badge"
      });
    }
    const cache = this.app.metadataCache.getFileCache(file);
    const desc = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.description;
    if (desc) {
      el.createEl("p", {
        text: String(desc).slice(0, 100),
        cls: "smart-link-result-snippet"
      });
    }
  }
  onChooseSuggestion(file, evt) {
    var _a, _b;
    const cache = this.app.metadataCache.getFileCache(file);
    const title = String((_b = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.title) != null ? _b : file.basename);
    this.editor.replaceSelection(`[[${title}]]`);
  }
  renderPills() {
    if (!this.pillBar)
      return;
    this.pillBar.empty();
    const visibleCollections = this.settings.visibleCollections;
    const allCollections = ["", ...Object.values(COLLECTION_MAP)];
    const pills = visibleCollections.length === 0 ? allCollections : ["", ...visibleCollections];
    for (const col of pills) {
      const label = col === "" ? "All" : col;
      const isActive = col === this.activeCollection;
      const btn = this.pillBar.createEl("button", {
        text: label,
        cls: "smart-link-pill" + (isActive ? " smart-link-pill--active" : "")
      });
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        this.activeCollection = col;
        this.renderPills();
        this.updateSuggestions();
      });
    }
  }
  updateSuggestions() {
    const event = new Event("input", { bubbles: true });
    this.inputEl.dispatchEvent(event);
  }
};

// src/main.ts
var SmartLinkPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SmartLinkSettingTab(this.app, this));
    this.addCommand({
      id: "smart-link-insert",
      name: "Insert Smart Link",
      editorCallback: (editor) => {
        new SmartLinkModal(this.app, editor, this.settings).open();
      }
    });
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
