/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmartLinkPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var DEFAULT_SETTINGS = {
  visibleCollections: [],
  maxResults: 50,
  defaultCollection: "",
  showUncreatedLinks: true,
  hideImageLinks: true,
  triggerPrefix: "s["
};

// src/settingsTab.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var COLLECTION_MAP = {
  "Content/Claims": "claims",
  "Content/Concepts": "concepts",
  "Content/Maps": "maps",
  "Content/Posts": "posts",
  "Content/Insights": "insights",
  "Sources/Books": "books",
  "Sources/Journals": "journals",
  "Sources/Research": "research"
};
function getCollection(filePath) {
  let best = "";
  let bestLen = -1;
  for (const [prefix, label] of Object.entries(COLLECTION_MAP)) {
    if (filePath.startsWith(prefix + "/") && prefix.length > bestLen) {
      best = label;
      bestLen = prefix.length;
    }
  }
  return best || "other";
}
var ALL_COLLECTIONS = Object.values(COLLECTION_MAP);

// src/settingsTab.ts
var SmartLinkSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Smart Link Settings").setHeading();
    new import_obsidian.Setting(containerEl).setName("Max results").setDesc("Maximum number of results to show in the modal").addSlider(
      (slider) => slider.setLimits(10, 100, 5).setValue(this.plugin.settings.maxResults).onChange(async (value) => {
        this.plugin.settings.maxResults = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Trigger prefix").setDesc("Type this snippet to open the Smart Link picker inline (default: s[)").addText(
      (text) => text.setValue(this.plugin.settings.triggerPrefix).onChange(async (value) => {
        this.plugin.settings.triggerPrefix = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Default collection").setDesc("Collection to show by default when opening the picker (leave empty for 'All')").addDropdown((dropdown) => {
      dropdown.addOption("", "All");
      for (const collection of ALL_COLLECTIONS) {
        dropdown.addOption(collection, collection);
      }
      dropdown.setValue(this.plugin.settings.defaultCollection).onChange(async (value) => {
        this.plugin.settings.defaultCollection = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(containerEl).setName("Show uncreated links").setDesc("Include links that don't have a corresponding file yet").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showUncreatedLinks).onChange(async (value) => {
        this.plugin.settings.showUncreatedLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Hide image links").setDesc("Exclude uncreated links ending with .png, .jpg, or .webp").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.hideImageLinks).onChange(async (value) => {
        this.plugin.settings.hideImageLinks = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "Visible Collections" });
    containerEl.createEl("p", { text: "Check to show collections in the filter pills" });
    for (const collection of ALL_COLLECTIONS) {
      new import_obsidian.Setting(containerEl).setName(collection).addToggle(
        (toggle) => toggle.setValue(this.plugin.settings.visibleCollections.includes(collection)).onChange(async (value) => {
          const idx = this.plugin.settings.visibleCollections.indexOf(collection);
          if (value && idx === -1) {
            this.plugin.settings.visibleCollections.push(collection);
          } else if (!value && idx !== -1) {
            this.plugin.settings.visibleCollections.splice(idx, 1);
          }
          await this.plugin.saveSettings();
        })
      );
    }
  }
};

// src/views/smartLinkModal.ts
var import_obsidian3 = require("obsidian");

// src/linkEngine.ts
var import_obsidian2 = require("obsidian");
var LinkEngine = class {
  constructor(app, settings) {
    this.index = /* @__PURE__ */ new Map();
    this.allFiles = [];
    this.uncreatedLinks = [];
    this.backlinkCounts = /* @__PURE__ */ new Map();
    this.app = app;
    this.settings = settings;
  }
  /** Build the composite search index and uncreated-links list. Call once per open. */
  buildIndex() {
    var _a;
    this.allFiles = this.app.vault.getMarkdownFiles();
    this.index.clear();
    for (const file of this.allFiles) {
      const cache = this.app.metadataCache.getFileCache(file);
      this.index.set(file, this.buildCompositeString(file, cache));
    }
    this.backlinkCounts.clear();
    const resolved = this.app.metadataCache.resolvedLinks;
    for (const links of Object.values(resolved)) {
      for (const targetPath of Object.keys(links)) {
        this.backlinkCounts.set(
          targetPath,
          ((_a = this.backlinkCounts.get(targetPath)) != null ? _a : 0) + 1
        );
      }
    }
    this.uncreatedLinks = [];
    if (this.settings.showUncreatedLinks) {
      const imageExts = /\.(png|jpg|webp)$/i;
      const seen = /* @__PURE__ */ new Set();
      const unresolved = this.app.metadataCache.unresolvedLinks;
      for (const links of Object.values(unresolved)) {
        for (const linkName of Object.keys(links)) {
          if (this.settings.hideImageLinks && imageExts.test(linkName))
            continue;
          seen.add(linkName);
        }
      }
      this.uncreatedLinks = Array.from(seen).sort();
    }
  }
  buildCompositeString(file, cache) {
    var _a, _b, _c, _d;
    const fm = (_a = cache == null ? void 0 : cache.frontmatter) != null ? _a : {};
    const parts = [
      file.basename,
      String((_b = fm.title) != null ? _b : "").trim(),
      Array.isArray(fm.aliases) ? fm.aliases.join(" ") : String((_c = fm.aliases) != null ? _c : "").trim(),
      String((_d = fm.description) != null ? _d : "").trim()
    ];
    return parts.filter(Boolean).join(" | ");
  }
  getBacklinkCount(file) {
    var _a;
    return (_a = this.backlinkCounts.get(file.path)) != null ? _a : 0;
  }
  getSuggestions(query, activeCollection) {
    var _a;
    let candidates = [...this.allFiles];
    if (activeCollection) {
      candidates = candidates.filter(
        (f) => getCollection(f.path) === activeCollection
      );
    } else {
      const visibleCollections = this.settings.visibleCollections;
      if (visibleCollections.length > 0) {
        candidates = candidates.filter(
          (f) => visibleCollections.includes(getCollection(f.path))
        );
      }
    }
    if (!query.trim()) {
      const fileItems = candidates.slice(0, this.settings.maxResults).map((f) => ({ type: "file", file: f }));
      if (this.settings.showUncreatedLinks) {
        const remaining = this.settings.maxResults - fileItems.length;
        const uncreatedItems = this.uncreatedLinks.slice(0, remaining).map((name) => ({ type: "uncreated", name }));
        return [...fileItems, ...uncreatedItems];
      }
      return fileItems;
    }
    const matcher = (0, import_obsidian2.prepareFuzzySearch)(query);
    const scored = [];
    for (const file of candidates) {
      const composite = (_a = this.index.get(file)) != null ? _a : file.basename;
      const result = matcher(composite);
      if (result) {
        scored.push({ item: { type: "file", file }, score: result.score });
      }
    }
    if (this.settings.showUncreatedLinks) {
      for (const name of this.uncreatedLinks) {
        const result = matcher(name);
        if (result) {
          scored.push({ item: { type: "uncreated", name }, score: result.score });
        }
      }
    }
    scored.sort((a, b) => b.score - a.score);
    return scored.slice(0, this.settings.maxResults).map((s) => s.item);
  }
  /** Resolve the text to insert inside [[...]] for a suggestion. */
  getLinkText(item) {
    var _a, _b, _c;
    return item.type === "file" ? String(
      (_c = (_b = (_a = this.app.metadataCache.getFileCache(item.file)) == null ? void 0 : _a.frontmatter) == null ? void 0 : _b.title) != null ? _c : item.file.basename
    ) : item.name;
  }
  /** Render a single suggestion row. Shared by modal and inline popup. */
  renderItem(item, el) {
    var _a;
    if (item.type === "uncreated") {
      el.addClass("smart-link-result--uncreated");
      const topLine2 = el.createDiv({ cls: "smart-link-result-top" });
      topLine2.createEl("span", { text: item.name, cls: "smart-link-result-title" });
      topLine2.createEl("span", {
        text: "uncreated",
        cls: "smart-link-result-badge smart-link-result-badge--uncreated"
      });
      return;
    }
    const { file } = item;
    const collection = getCollection(file.path);
    const backlinks = this.getBacklinkCount(file);
    const topLine = el.createDiv({ cls: "smart-link-result-top" });
    topLine.createEl("span", { text: file.basename, cls: "smart-link-result-title" });
    if (collection) {
      topLine.createEl("span", {
        text: collection,
        cls: "smart-link-result-badge"
      });
    }
    topLine.createEl("span", {
      text: `\u21A9 ${backlinks}`,
      cls: "smart-link-result-backlinks"
    });
    const cache = this.app.metadataCache.getFileCache(file);
    const desc = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.description;
    if (desc) {
      el.createEl("p", {
        text: String(desc).slice(0, 100),
        cls: "smart-link-result-snippet"
      });
    }
  }
};

// src/views/smartLinkModal.ts
var SmartLinkModal = class extends import_obsidian3.SuggestModal {
  constructor(app, editor, settings) {
    super(app);
    this.activeCollection = "";
    this.pillBar = null;
    this.editor = editor;
    this.settings = settings;
    this.engine = new LinkEngine(app, settings);
    this.modalEl.addClass("smart-link-modal");
  }
  onOpen() {
    this.engine.buildIndex();
    this.activeCollection = this.settings.defaultCollection;
    this.pillBar = this.modalEl.createDiv({ cls: "smart-link-pill-bar" });
    this.modalEl.prepend(this.pillBar);
    this.renderPills();
    super.onOpen();
    setTimeout(() => this.inputEl.focus(), 10);
  }
  getSuggestions(query) {
    return this.engine.getSuggestions(query, this.activeCollection);
  }
  renderSuggestion(item, el) {
    this.engine.renderItem(item, el);
  }
  onChooseSuggestion(item) {
    this.editor.replaceSelection(`[[${this.engine.getLinkText(item)}]]`);
  }
  renderPills() {
    if (!this.pillBar)
      return;
    this.pillBar.empty();
    const visibleCollections = this.settings.visibleCollections;
    const allCollections = ["", ...Object.values(COLLECTION_MAP)];
    const pills = visibleCollections.length === 0 ? allCollections : ["", ...visibleCollections];
    for (const col of pills) {
      const label = col === "" ? "All" : col;
      const isActive = col === this.activeCollection;
      const btn = this.pillBar.createEl("button", {
        text: label,
        cls: "smart-link-pill" + (isActive ? " smart-link-pill--active" : "")
      });
      btn.addEventListener("click", (e) => {
        e.preventDefault();
        this.activeCollection = col;
        this.renderPills();
        this.refreshSuggestions();
      });
    }
  }
  refreshSuggestions() {
    setTimeout(() => {
      const event = new Event("input", { bubbles: true });
      this.inputEl.dispatchEvent(event);
    }, 0);
  }
};

// src/views/smartLinkSuggest.ts
var import_obsidian4 = require("obsidian");
var SmartLinkSuggest = class extends import_obsidian4.EditorSuggest {
  constructor(app, settings) {
    super(app);
    this.settings = settings;
    this.engine = new LinkEngine(app, settings);
  }
  /**
   * Rebuild the search index off the keystroke hot path. Running buildIndex
   * synchronously inside onTrigger blocked the main thread long enough to
   * blur the editor, which closed the popup before it could attach.
   */
  refreshIndex() {
    this.engine.buildIndex();
  }
  onTrigger(cursor, editor, _file) {
    var _a;
    const beforeCursor = editor.getLine(cursor.line).slice(0, cursor.ch);
    const prefix = this.settings.triggerPrefix;
    if (!prefix)
      return null;
    const escaped = prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const match = beforeCursor.match(new RegExp("(?<!\\w)" + escaped + "([^\\]\\n]*)$"));
    if (!match)
      return null;
    return {
      start: { line: cursor.line, ch: (_a = match.index) != null ? _a : 0 },
      end: cursor,
      query: match[1]
    };
  }
  getSuggestions(context) {
    return this.engine.getSuggestions(context.query, this.settings.defaultCollection);
  }
  renderSuggestion(item, el) {
    this.engine.renderItem(item, el);
  }
  selectSuggestion(item, _evt) {
    var _a, _b, _c, _d;
    const context = this.context;
    if (!context)
      return;
    const editor = context.editor;
    const replacement = `[[${this.engine.getLinkText(item)}]]`;
    let end = context.end;
    const trailingOpen = (_b = (_a = this.settings.triggerPrefix.match(/\[+$/)) == null ? void 0 : _a[0].length) != null ? _b : 0;
    if (trailingOpen > 0) {
      const after = editor.getLine(context.end.line).slice(context.end.ch, context.end.ch + trailingOpen);
      const closers = (_d = (_c = after.match(/^\]+/)) == null ? void 0 : _c[0].length) != null ? _d : 0;
      if (closers > 0) {
        end = { line: context.end.line, ch: context.end.ch + closers };
      }
    }
    editor.replaceRange(replacement, context.start, end);
    editor.setCursor({
      line: context.start.line,
      ch: context.start.ch + replacement.length
    });
    this.close();
  }
};

// src/main.ts
var SmartLinkPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
    this.suggest = null;
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new SmartLinkSettingTab(this.app, this));
    this.suggest = new SmartLinkSuggest(this.app, this.settings);
    this.registerEditorSuggest(this.suggest);
    this.app.workspace.onLayoutReady(() => {
      var _a;
      return (_a = this.suggest) == null ? void 0 : _a.refreshIndex();
    });
    this.registerEvent(
      this.app.metadataCache.on(
        "resolved",
        (0, import_obsidian5.debounce)(() => {
          var _a;
          return (_a = this.suggest) == null ? void 0 : _a.refreshIndex();
        }, 2e3, true)
      )
    );
    this.addCommand({
      id: "smart-link-insert",
      name: "Insert Smart Link",
      editorCallback: (editor) => {
        new SmartLinkModal(this.app, editor, this.settings).open();
      }
    });
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
